version: '3'
services:
  db:
    image: mysql/mysql-server:latest
    restart: unless-stopped
    container_name: mysql_db_container
    environment:
      - MYSQL_DATABASE=hostel
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3310:3310'
    volumes:
      - db:/var/lib/mysql12
    networks:
      - backend-mysql

networks:
  backend-mysql:
    driver: bridge

volumes:
  db:
