version: "2.4"
services:
  mysqldb-container:
    image: mysql/mysql-server
    container_name: mysqldb-container

    networks:
      - my_net
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=hostel
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password

  backend:
    image: bony211298/hostel_backend
    container_name: backend
    networks:
      - my_net
    ports:
      - "8085:8085"
    links:
      - mysqldb-container
    depends_on:
      mysqldb-container:
        condition: service_healthy

  frontend:
    image: bony211298/frontend_hostel
    container_name: frontend
    networks:
      - my_net
    ports:
      - "4200:4200"
    depends_on:
      - backend


networks:
  my_net:
